// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVEUQKXYoRlgnQ10dpIbeT0iFIWrS1zbQ',
    appId: '1:189957318522:web:39503bf447627690df98c3',
    messagingSenderId: '189957318522',
    projectId: 'whatsapp-658e3',
    authDomain: 'whatsapp-658e3.firebaseapp.com',
    storageBucket: 'whatsapp-658e3.appspot.com',
    measurementId: 'G-6X98MSK1LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ZIKvM39flAzlQFvJJxeHFNGnFRDuR0k',
    appId: '1:189957318522:android:f30d4ca2f5e0d77adf98c3',
    messagingSenderId: '189957318522',
    projectId: 'whatsapp-658e3',
    storageBucket: 'whatsapp-658e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlwYZzGRzXO4qfcsktveKWbwn-oBEPgx4',
    appId: '1:189957318522:ios:2607911f7d683543df98c3',
    messagingSenderId: '189957318522',
    projectId: 'whatsapp-658e3',
    storageBucket: 'whatsapp-658e3.appspot.com',
    iosClientId: '189957318522-712vseko4kglc4g8l8nta8rv8onh4bad.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlwYZzGRzXO4qfcsktveKWbwn-oBEPgx4',
    appId: '1:189957318522:ios:2607911f7d683543df98c3',
    messagingSenderId: '189957318522',
    projectId: 'whatsapp-658e3',
    storageBucket: 'whatsapp-658e3.appspot.com',
    iosClientId: '189957318522-712vseko4kglc4g8l8nta8rv8onh4bad.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
